version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
configuration: Release
before_build:
   - nuget restore src
build:
  project: src/Nager.VideoStream.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
deploy:
  provider: NuGet
  api_key:
    secure: DSix/vA4f2Bn/U8J2+Q4BufzNClNNL+enzqTdDNo2449kclgbfRV8DDB9aw9iS6R
  artifact: /.*\.nupkg/
